services:
  r-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: alexfariakof/rstudio-base:latest
    container_name: rstudio-base # docker exec -it rstudio-base bash
    command: ["true"]

  