#make up
include:
  - path: docker-compose.network.yml
  - path: docker-compose.volume.yml

services:
  rs-infra:
    image: alpine:3.22
    container_name: rs-infra
    profiles: ["init"]
    command: ["true"]
    networks:
      - rs-network
    pull_policy: if_not_present
