services:
  rstudio:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rstudio-dev-base
    image: alexfariakof/rstudio-dev-base:latest
    ports:
      - "8787:8787" # http://localhost:8787/ user: rstudio password: toor
      - "8888:8888" # http://localhost:8888/ 
    environment:
      PASSWORD: "toor"
    volumes:
      - ../workspace:/home/rstudio/workspace
      - vscode-extensions:/.vscode/extensions:/rstudio/.vscode-server/extensions
    restart: unless-stopped
    command: ["/usr/local/bin/docker-entrypoint.sh"]    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  vscode-extensions: