services:
  rstudio-pos-devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio-pos-devcontainer  # docker exec -it rstudio-devcontaier bash
    environment:
      PASSWORD: "toor"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SPARK_MASTER: spark://spark-master:7077      
    ports:
      - "8787:8787" # http://localhost:8787/ user: rstudio password: toor
      - "8888:8888" # http://localhost:8888/
    volumes:
      - ..:/workspace:cached      
      - ../src:/home/rstudio/src/r:cached
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
    restart: unless-stopped
    #entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]    
    networks:
      - rs-network    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

networks:
  rs-network:
    external: true

