services:
  r-dev-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: alexfariakof/rstudio-dev-base:latest
    container_name: rstudio-dev-base # docker exec -it rstudio-dev-bases bash
    command: sleep infinity

  